### ISSUE TITLE
dataset config yaml

### ISSUE THREAD

**Issue by YatongChen0603** [Multi-IoT/MultiIoT#3]
I wonder if you can provide the file, 'configs/data/pretrain/EN.yaml', looking forward to your reply.

**Comment by Multi-IoT** [comment]
Hi, thanks for your interest! We will update it soon.

**Comment by HaiC149149** [comment]
Hi did you find this ?

**Comment by YatongChen0603** [comment]
> Hi did you find this ?

Not yet
